config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :metadatas,     only: %i[index]
  # Defines the root path route ("/")
  root "metadatas#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/metadata.rb
class Metadata
  include ActiveModel::Model

  def self.parse_xml
    xml_data = File.read(Rails.root.join("tmp/metadata_cached_file.xml"))
    xml = Nokogiri::XML(xml_data)
    metadatas = xml.xpath('//meta_data')

    metadatas.map do |m|
      full_title = m.at_xpath('./title').text
      next if "---------------" == full_title # 書籍を参照不可能なメタデータは除外する
      label = full_title.match(/\(([^)]{2,})\)$/) # タイトルにレーベル名と思しき部分があるなら抽出
      asin = m.at_xpath('./ASIN').text
      author = m.at_xpath('./authors/author[1]') # 共著の場合は一人目を著者とする
      publisher = m.at_xpath('./publishers/publisher[1]') # 共同出版の場合は１社目を出版社とする

      {
        desktop_url: "kindle://book/?action=open&asin=#{asin}",           # アプリで書籍を開くカスタムURLスキーム
        web_url: "https://read.amazon.co.jp/manga/#{asin}",               # ブラウザ版ビューワーで書籍を開くURL
        asin: asin,                                                       # 書籍識別番号
        title: label ? full_title.gsub(label[0], '').rstrip : full_title, # レーベル部分を除いたタイトル
        author: author&.text,                                             # 著者名
        author_pronunciation: author&.attr('pronunciation'),         # 著者名読み
        label: label ? label[1] : "_",                                    # レーベル名
        publisher: publisher&.text,                                       # 出版社名
        publisher_pronunciation: publisher&.attr('pronunciation'),   # 出版社名読み
        publication_date: m.at_xpath('./publication_date').text,          # 出版日
        purchase_date: m.at_xpath('./purchase_date').text,                # 購入日
        origin: m.at_xpath('./origins/origin[1]').text,                   # 取得元
      }
    end.compact
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/metadatas_controller.rb
class MetadatasController < ApplicationController
  def index
    @metadatas = Metadata.parse_xml

    @authors = @metadatas.map{|hash| hash[:author]}.uniq
    if params[:filter_type].present?
      @metadatas.filter!{|metadata| metadata[params[:filter_type].to_sym] == params[:filter_val]}
    end
    @metadatas.sort!{|m1, m2| sort_logic(params[:sort_order], m1[params[:sort_column]&.to_sym], m2[params[:sort_column]&.to_sym])}
  end
  
  private
  
  def sort_logic(ord, m1, m2)
    if m1.blank?
      1
    elsif m2.blank?
      -1
    else
      if ord.to_sym == :desc
        Date.parse(m2) <=> Date.parse(m1)
      elsif ord.to_sym == :asc
        Date.parse(m1) <=> Date.parse(m2)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "uri"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyKindleLibrary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/metadatas/index.html.erb
<div popover id="modal-author-filter">
  <select name="example" class="filter" data-type="author">
    <%- @authors.each do |author| %>
      <option value=<%=URI.encode_www_form_component(author)%>><%= author %></option>
    <%- end %>
  </select>
</div>
<table>
  <tr>
    <th>forPC</th>
    <th>ブラウザ</th>
    <th>ASIN</th>
    <th>タイトル</th>
    <th>著者 <button popovertarget="modal-author-filter">↓</button></th>
    <th>レーベル</th>
    <th>出版社</th>
    <th>出版日
      <%= link_to "▲", metadatas_path(sort_column: :publication_date, sort_order: :asc), class: "sort-direction" %>
      <%= link_to "▼", metadatas_path(sort_column: :publication_date, sort_order: :desc), class: "sort-direction" %>
    </th>
    <th>購入日
      <%= link_to "▲", metadatas_path(sort_column: :purchase_date, sort_order: :asc), class: "sort-direction" %>
      <%= link_to "▼", metadatas_path(sort_column: :purchase_date, sort_order: :desc), class: "sort-direction" %>
    </th>
    <th>取得元</th>
  </tr>
  <% @metadatas.each do |m| %>
    <tr>
      <td><a href =<%= m[:desktop_url] %>>link</a></td>
      <td><%= link_to "link", m[:web_url] %></td>
      <td><%= m[:asin] %></td>
      <td><%= m[:title] %></td>
      <td><%= m[:author] %></td>
      <td><%= m[:label] %></td>
      <td><%= m[:publisher] %></td>
      <td><%= m[:publication_date] %></td>
      <td><%= m[:purchase_date] %></td>
      <td><%= m[:origin] %></td>
    </tr>
  <% end %>
</table>

<script>
  document.querySelector('select.filter').addEventListener("change",function(e) {
    const filter_type = e.target.getAttribute("data-type");
    const filter_val = e.target.value;
    location.href = `<%= metadatas_path %>?filter_type=${filter_type}&filter_val=${filter_val}`;
    console.log(filter_val);
    console.log(e.target.value);
  })
</script>